### PR TITLE
custom marshaller and unmarshaller ed25519.go, uses rawstring for json.

### LINKED ISSUE #149: Add Custom JSON Marshaller to Pubkey

### PR DESCRIPTION
**Pull request by oten91**
closes #149

### CODE REVIEW

**Review by andrewnguyen22 — CHANGES_REQUESTED** [review]
We should add marshalJSON and unmarshalJSON to the public key interface and appy it to SECP256K1

**Comment by oten91** [comment]
> We should add marshalJSON and unmarshalJSON to the public key interface and apply it to SECP256K1

I think adding marshalJSON and UnmarshalJSON to the interface and keeping compatibility with amino could mean a rewrite of some functionalities and maybe loss of flexibility (currently we need unmarshal to have pointer receiver for amino compatibility, if added as part of interface without changes current keys wont comply with the public key interface).

Will be implementing methods in SECP256K1 without changing the interface as an intermediate solution.

@andrewnguyen22 Let me know what you think.

**Review by edjroz — APPROVED** [review]
LGTM

**Comment by andrewnguyen22** [comment]
> > We should add marshalJSON and unmarshalJSON to the public key interface and apply it to SECP256K1
> 
> I think adding marshalJSON and UnmarshalJSON to the interface and keeping compatibility with amino could mean a rewrite of some functionalities and maybe loss of flexibility (currently we need unmarshal to have pointer receiver for amino compatibility, if added as part of interface without changes current keys wont comply with the public key interface).
> 
> Will be implementing methods in SECP256K1 without changing the interface as an intermediate solution.
> 
> @andrewnguyen22 Let me know what you think.

Sounds good @oten91

**Review by andrewnguyen22 — APPROVED** [review]

**Pull request merged**
